from pathlib import Path
import html

ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'nettside'
ARROW='<span aria-hidden="true">↗</span>'

def header(active):
    links=[('index.html','Hjem','home'),('index.html#tjenester','Tjenester','services'),('om-oss.html','Om oss','about')]
    nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if key==active else '')+f'>{label}</a>' for url,label,key in links)
    return f'''<a class="skip-link" href="#innhold">Hopp til innhold</a>
<header class="site-header"><div class="container header-inner">
<a class="brand" href="index.html" aria-label="Eldrehjelperne UB – hjem"><img src="assets/3650e.png" width="72" height="72" alt=""><span>Eldrehjelperne<span class="brand-ub"> UB</span><small>Ung omsorg, tidløse bånd</small></span></a>
<button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" hidden><span>Meny</span><span class="menu-icon" aria-hidden="true"></span></button>
<nav id="main-nav" aria-label="Hovedmeny">{nav}<a class="button button-small" href="kontakt.html" {'aria-current="page"' if active=='contact' else ''}>Ta kontakt {ARROW}</a></nav>
</div></header>'''

def footer():
    return '''<footer class="site-footer"><div class="container footer-grid"><div><a class="brand footer-brand" href="index.html"><img src="assets/3650e.png" alt="" width="72" height="72"><span>Eldrehjelperne UB<small>Ung omsorg, tidløse bånd</small></span></a><p>Praktisk hjelp. Hyggelig selskap.<br>Små øyeblikk som betyr noe.</p></div><div><h2>Finn frem</h2><a href="index.html#tjenester">Våre tjenester</a><a href="om-oss.html">Om oss</a><a href="kontakt.html">Ta kontakt</a></div><div><h2>La oss snakke</h2><a href="tel:+4745017140">450 17 140</a><a href="mailto:akselbistad@gmail.com">akselbistad@gmail.com</a><span>Nydalen · Oslo</span></div></div><div class="container footer-bottom"><span>Eldrehjelperne UB</span><a href="prosjekt.html">Om nettsideprosjektet <span aria-hidden="true">↗</span></a><a href="personvern.html">Personvern i demoen</a></div></footer>'''

def cta():
    return f'''<section class="contact-banner"><div class="container contact-banner-inner"><div><span class="eyebrow">Vi starter med en samtale</span><h2>Et lite hei kan være<br>starten på noe fint.</h2></div><div><p>Fortell oss hva du ønsker hjelp med, så kan vi snakke om hva som passer.</p><a class="button button-white" href="kontakt.html">Ta kontakt {ARROW}</a><a class="call-link" href="tel:+4745017140">Eller ring 450 17 140</a></div></div></section>'''

def page(filename,title,description,body,active=''):
    doc=f'''<!doctype html>
<html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{html.escape(description,quote=True)}"><meta name="theme-color" content="#00C4D7"><meta property="og:title" content="{html.escape(title,quote=True)}"><meta property="og:description" content="{html.escape(description,quote=True)}"><meta property="og:type" content="website"><meta property="og:locale" content="nb_NO"><title>{title}</title><link rel="icon" type="image/png" href="assets/3650e.png"><link rel="stylesheet" href="fonts.css"><link rel="stylesheet" href="styles.css"><script type="module" src="site.js"></script></head><body>{header(active)}<main id="innhold">{body}</main>{footer()}</body></html>'''
    (SITE/filename).write_text(doc,encoding='utf-8')

services=[('besok','6c3d4.png','Besøksvenn','Tid til en god samtale.','En å dele historier med, lese avisen sammen med eller utfordre i et brettspill.','Samtaler og selskap|Spill og hyggelige aktiviteter'),('folge','6840d.png','Følgetjeneste','Litt enklere å komme seg ut.','Selskap på handleturen, en tur i nabolaget eller på vei til en avtale.','Turer og butikkbesøk|Følge til en avtale'),('hjem','622a4.png','Hjemmehjelp','En hjelpende hånd i hverdagen.','Praktisk hjelp med små oppgaver hjemme eller i hagen, etter nærmere avtale.','Små oppgaver i hjemmet|Praktisk hjelp i hagen')]
cards=''
for i,(key,asset,name,subtitle,desc,examples) in enumerate(services,1):
    cards+=f'''<article class="service-card" data-reveal><div class="service-card-top"><span class="index-label">0{i}</span><img src="assets/{asset}" alt="" width="350" height="350" loading="lazy"></div><h3>{name}</h3><p class="card-subtitle">{subtitle}</p><p>{desc}</p><ul>{''.join('<li>'+x+'</li>' for x in examples.split('|'))}</ul><a class="text-link" href="kontakt.html?tjeneste={key}">Spør om {name.lower()} {ARROW}</a></article>'''

page('index.html','Eldrehjelperne UB – Ung omsorg, tidløse bånd','Praktisk hjelp og hyggelig selskap for eldre. Bli kjent med Eldrehjelperne UB fra Nydalen i Oslo.',f'''
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow"><span class="status-dot" aria-hidden="true"></span>Ungdomsbedrift fra Nydalen, Oslo</span><h1>Ung omsorg.<br><span>Tidløse bånd.</span></h1><p class="hero-description">Litt hjelp i hverdagen.<br>Litt mer glede i livet.</p><p>Vi skaper rom for hyggelige samtaler, små opplevelser og praktisk hjelp — med tid til mennesket.</p><div class="hero-actions"><a class="button" href="kontakt.html">La oss ta en prat {ARROW}</a><a class="text-link" href="#tjenester">Se hva vi kan hjelpe med <span aria-hidden="true">↓</span></a></div><div class="hero-note"><span class="note-mark" aria-hidden="true">♡</span><span>For eldre og deres pårørende.<br><strong>Med glede i sentrum.</strong></span></div></div>
<div class="hero-art" aria-label="Illustrasjon av hyggelig selskap"><div class="orbit orbit-one" aria-hidden="true"></div><div class="orbit orbit-two" aria-hidden="true"></div><div class="art-label"><span aria-hidden="true">✦</span> Tid til hverandre</div><img class="hero-illustration" src="assets/6c3d4.png" alt="To personer deler en samtale ved et bord" width="350" height="350" fetchpriority="high"><div class="art-note"><span class="art-note-icon" aria-hidden="true">♡</span><div><strong>De små øyeblikkene.</strong><span>De store forskjellene.</span></div></div><span class="art-caption">Sammen er hverdagen litt hyggeligere.</span></div></div><div class="container hero-bottom"><span>Besøksvenn</span><span aria-hidden="true">✦</span><span>Følgetjeneste</span><span aria-hidden="true">✦</span><span>Hjemmehjelp</span><a href="#tjenester" aria-label="Utforsk tjenestene"><span aria-hidden="true">↓</span></a></div></section>
<section class="section" id="tjenester"><div class="container"><div class="section-heading" data-reveal><div><span class="eyebrow">Hva kan vi gjøre for deg?</span><h2>Små ting.<br><span>Stor betydning.</span></h2></div><p>Noen ganger trenger man en hjelpende hånd. Andre ganger er det bare godt å ha noen å være sammen med.</p></div><div class="service-grid">{cards}</div></div></section>
<section class="joy-section"><div class="container joy-inner" data-reveal><span class="eyebrow">Det handler om mer enn hjelp</span><h2>Vi setter <span>glede</span> først.</h2><p>En god samtale. En tur ut. Et nytt minne.<br>Det er plass til mer av det som gjør hverdagen god.</p><a class="text-link" href="om-oss.html">Bli kjent med oss {ARROW}</a><img src="assets/3650e.png" width="120" height="120" alt="" loading="lazy"></div></section>
<section class="section"><div class="container"><div class="section-heading" data-reveal><div><span class="eyebrow">En enkel start</span><h2>Fra et hei<br>til en hyggelig avtale.</h2></div><p>Du trenger ikke ha alle svarene. Vi starter med å snakke om hva du ønsker.</p></div><ol class="process-grid"><li data-reveal><span class="process-number">01</span><h3>Fortell oss litt</h3><p>Ring eller send en e-post om hva du ønsker hjelp eller selskap til.</p></li><li data-reveal><span class="process-number">02</span><h3>Vi snakker sammen</h3><p>Vi avklarer ønskene dine og diskuterer hva vi kan bidra med.</p></li><li data-reveal><span class="process-number">03</span><h3>Vi avtaler detaljene</h3><p>Tid, sted og aktivitet avtales sammen før et eventuelt besøk.</p></li></ol></div></section>
<section class="section activities-section"><div class="container"><div class="section-heading" data-reveal><div><span class="eyebrow">Tid til det som er hyggelig</span><h2>Hva har du<br>lyst til å gjøre?</h2></div><p>En opplevelse trenger ikke være stor for å bety mye. Her er noen ideer til noe vi kan gjøre sammen.</p></div><div class="activity-grid"><article class="activity-card" data-reveal><div><span class="eyebrow">Ut og oppleve</span><h3>Musikk. Minner.<br>Et hyggelig avbrekk.</h3><p>Kanskje en konsert eller et kafébesøk? Vi kan snakke om mulighetene sammen.</p><a class="text-link" href="kontakt.html?tjeneste=besok">Finn på noe hyggelig {ARROW}</a></div><img src="assets/64568.png" alt="Illustrasjon av musikere på en konsert" width="557" height="572" loading="lazy"></article><article class="activity-card" data-reveal><div><span class="eyebrow">En tur sammen</span><h3>Frisk luft.<br>Godt selskap.</h3><p>En liten tur i nabolaget, en pause på en benk og tid til en prat.</p><a class="text-link" href="kontakt.html?tjeneste=folge">Spør om følge {ARROW}</a></div><img src="assets/505bf.png" alt="Illustrasjon av et tre og en parkbenk" width="533" height="533" loading="lazy"></article></div></div></section>
<section class="section"><div class="container about-preview" data-reveal><div class="about-preview-visual"><img src="assets/59e92.png" width="512" height="512" alt="En hånd som vinker" loading="lazy"><span>Hei fra Eldrehjelperne!</span></div><div><span class="eyebrow">Menneskene bak</span><h2>Unge mennesker.<br>Et varmt engasjement.</h2><p>Vi er en ungdomsbedrift ved Nydalen videregående skole i Oslo. Utgangspunktet vårt er enkelt: Alle fortjener omsorg, selskap og glede i hverdagen, uansett alder.</p><a class="button" href="om-oss.html">Les om oss {ARROW}</a></div></div></section>
<section class="section faq-section"><div class="container faq-grid"><div data-reveal><span class="eyebrow">Lurer du på noe?</span><h2>La oss gjøre<br>det litt enklere.</h2><p>Du kan også ringe oss.<br><a class="text-link" href="tel:+4745017140">450 17 140 {ARROW}</a></p></div><div class="faq-list"><details><summary>Hva kan dere hjelpe med?<span aria-hidden="true">+</span></summary><p>Vi tilbyr sosialt selskap, følge og praktisk hjelp. Se tjenestene ovenfor, og kontakt oss for å avklare hva som er mulig for deg.</p></details><details><summary>Kan jeg ta kontakt for en pårørende?<span aria-hidden="true">+</span></summary><p>Ja, du kan ta kontakt for å diskutere hjelp eller selskap til en pårørende. Vi avklarer videre detaljer sammen.</p></details><details><summary>Hvordan avtaler jeg et besøk?<span aria-hidden="true">+</span></summary><p>Ring eller send en e-post. Tid, sted og innhold må avtales direkte. Et besøk er først avtalt når detaljene er bekreftet.</p></details><details><summary>Hva koster tjenestene?<span aria-hidden="true">+</span></summary><p>Kontakt oss for å avklare pris og hva avtalen omfatter før du bestemmer deg.</p></details><details><summary>Er dette en helsetjeneste?<span aria-hidden="true">+</span></summary><p>Tilbudet gjelder sosialt selskap og praktisk hjelp. Det erstatter ikke profesjonell helsehjelp eller medisinsk behandling.</p></details></div></div></section>
{cta()}''','home')

page('om-oss.html','Om oss – Eldrehjelperne UB','Bli kjent med ungdomsbedriften Eldrehjelperne UB fra Nydalen videregående skole.',f'''
<section class="page-hero"><div class="container page-hero-grid"><div><a class="breadcrumb" href="index.html">Hjem <span aria-hidden="true">/</span></a><span class="eyebrow">Hei, vi er Eldrehjelperne</span><h1>Ungt engasjement.<br><span>Varme forbindelser.</span></h1><p>En ungdomsbedrift fra Nydalen videregående skole i Oslo, med et ønske om å skape mer glede i hverdagen.</p><a class="text-link" href="#team">Bli kjent med teamet <span aria-hidden="true">↓</span></a></div><img src="assets/59e92.png" alt="En hånd som vinker hei" width="512" height="512"></div></section>
<section class="section"><div class="container story-grid" data-reveal><span class="eyebrow">Hvorfor Eldrehjelperne?</span><div><h2>Omsorg har<br>ingen aldersgrense.</h2><p class="lead">Vi ønsker at alle skal få den omsorgen de trenger, uansett alder.</p><p>Derfor tilbyr vi praktiske og sosiale tjenester til eldre som bor hjemme eller på institusjon. Det kan være en god samtale, hjelp med en oppgave eller selskap på en tur.</p><p>Det er dine ønsker som er utgangspunktet. Sammen kan vi snakke om hva du vil bruke tiden på, og hva vi kan bidra med.</p></div></div></section>
<section class="section team-section" id="team"><div class="container"><div class="section-heading" data-reveal><div><span class="eyebrow">Menneskene bak</span><h2>Et lite team.<br>Et felles engasjement.</h2></div><p>Dette er teamet presentert i den opprinnelige Eldrehjelperne-profilen.</p></div><div class="team-grid">{''.join(f'<article class="team-card" data-reveal><img src="assets/{asset}" alt="" width="346" height="346" loading="lazy"><span class="eyebrow">{role}</span><h3>{name}</h3></article>' for name,role,asset in [('Aksel','Daglig leder','a0a84.png'),('Sebastian','Markedsansvarlig','6cdbe.png'),('Bastian','Økonomisjef','6cdbe.png')])}</div></div></section>
<section class="section"><div class="container boundary-grid" data-reveal><img src="assets/6c3d4.png" alt="" width="350" height="350" loading="lazy"><div><span class="eyebrow">Med mennesket i sentrum</span><h2>Hjelp og selskap,<br>på dine premisser.</h2><p>Vi tilbyr sosialt selskap og praktisk hjelp. Vi avklarer oppgaver og forventninger sammen før et besøk.</p><p>Tilbudet erstatter ikke profesjonelle helse- og omsorgstjenester. Kontakt oss gjerne hvis du er usikker på om vi kan bidra.</p><a class="text-link" href="index.html#tjenester">Utforsk tjenestene {ARROW}</a></div></div></section>{cta()}''','about')

choices=''.join(f'''<label class="choice-card"><input type="radio" name="service" value="{key}" required><span class="choice-visual"><img src="assets/{asset}" alt="" width="80" height="80"><strong>{name}</strong><span>{subtitle}</span></span></label>''' for key,asset,name,subtitle,_,_ in services)
page('kontakt.html','Ta kontakt – Eldrehjelperne UB','Ring eller send en e-post til Eldrehjelperne. Utforsk en demonstrasjon av en veiledet besøksforespørsel.',f'''
<section class="contact-page section"><div class="container"><a class="breadcrumb" href="index.html">Hjem <span aria-hidden="true">/</span></a><div class="contact-layout"><aside class="contact-intro"><span class="eyebrow">Et hyggelig sted å starte</span><h1>La oss<br><span>ta en prat.</span></h1><p>Fortell oss hva du trenger. Vi kan sammen finne ut hva som passer.</p><div class="contact-method"><span class="eyebrow">Ring oss</span><a href="tel:+4745017140">450 17 140 {ARROW}</a></div><div class="contact-method"><span class="eyebrow">Send en e-post</span><a href="mailto:akselbistad@gmail.com">akselbistad@gmail.com {ARROW}</a></div><p class="contact-footnote">En avtale om besøk avklares direkte på telefon eller e-post.</p><img class="contact-sun" src="assets/3650e.png" width="120" height="120" alt=""></aside>
<div class="request-panel"><div class="demo-notice"><strong>Prøv en besøksforespørsel</strong><p>Dette skjemaet er en demo. Ingenting sendes eller lagres. For en ekte henvendelse, ring eller send e-post.</p></div><noscript><p>Skjemademoen trenger JavaScript. Du kan fortsatt kontakte oss på telefon eller e-post.</p></noscript><div id="request-app" hidden><ol class="stepper" aria-label="Steg i forespørselen"><li data-step-marker="0" aria-current="step"><span>1</span>Ønske</li><li data-step-marker="1"><span>2</span>Kontakt</li><li data-step-marker="2"><span>3</span>Oversikt</li></ol>
<form id="request-form" novalidate><div id="form-errors" class="error-summary" role="alert" hidden></div>
<fieldset data-step="0"><legend id="step-title-0" tabindex="-1">Hva ønsker du hjelp med?</legend><p class="field-intro">Velg det som passer best. Det er helt greit å være usikker.</p><div class="choice-grid">{choices}<label class="choice-card choice-unsure"><input type="radio" name="service" value="usikker" required><span class="choice-visual"><span class="unsure-symbol" aria-hidden="true">?</span><strong>Jeg er usikker</strong><span>Vi finner ut av det sammen.</span></span></label></div><p id="service-error" class="field-error" hidden></p></fieldset>
<fieldset data-step="1" hidden><legend id="step-title-1" tabindex="-1">Hvordan kan vi nå deg?</legend><p class="field-intro">Bruk gjerne eksempelopplysninger når du prøver demoen.</p><div class="field"><label for="name">Navn <span>(påkrevd)</span></label><input id="name" name="name" autocomplete="name" maxlength="100" required aria-describedby="name-error"><p class="field-error" id="name-error" hidden></p></div><div class="field"><label for="method">Ønsket kontaktmåte</label><select id="method" name="method"><option value="telefon">Telefon</option><option value="epost">E-post</option></select></div><div class="field"><label for="contact"><span id="contact-label">Telefonnummer</span> <span>(påkrevd)</span></label><input id="contact" name="contact" type="tel" autocomplete="tel" maxlength="120" required aria-describedby="contact-error"><p class="field-error" id="contact-error" hidden></p></div><div class="field"><label for="note">Hva tenker du på? <span>(valgfritt)</span></label><textarea id="note" name="note" rows="3" maxlength="500" aria-describedby="note-help"></textarea><p id="note-help" class="field-help">Ikke oppgi diagnoser eller sensitive helseopplysninger.</p></div></fieldset>
<fieldset data-step="2" hidden><legend id="step-title-2" tabindex="-1">Ser dette riktig ut?</legend><p class="field-intro">Her er en oversikt over demoforspørselen din. Du kan endre opplysningene før du prøver siste steg.</p><dl id="request-summary" class="request-summary"></dl><div class="edit-actions"><button type="button" class="text-button" data-edit="0">Endre ønske</button><button type="button" class="text-button" data-edit="1">Endre kontaktopplysninger</button></div><p class="review-note">Demoen bekrefter ikke et besøk. Ingen opplysninger sendes.</p></fieldset>
<div class="form-actions"><button type="button" id="back-button" class="button button-outline" hidden>Tilbake</button><button type="submit" id="next-button" class="button">Neste <span aria-hidden="true">→</span></button></div><p id="request-status" class="field-help" role="status" aria-live="polite"></p></form>
<div id="request-success" class="success-panel" hidden><span class="success-mark" aria-hidden="true">✓</span><h2 tabindex="-1">Takk for at du prøvde!</h2><p>Du har fullført demoen. Ingenting ble sendt, og det er ikke bestilt et besøk.</p><p>Vil du ta kontakt på ordentlig?</p><a class="button" href="tel:+4745017140">Ring 450 17 140 {ARROW}</a><a class="text-link" href="mailto:akselbistad@gmail.com">Send en e-post {ARROW}</a><button type="button" class="text-button" id="restart-button">Prøv demoen på nytt</button></div></div></div></div></div></section>''','contact')

page('prosjekt.html','Nettsideprosjektet – Eldrehjelperne UB','Designvalg, merkevare og teknisk løsning bak den nye Eldrehjelperne-nettsiden.',f'''
<section class="page-hero project-hero"><div class="container"><span class="eyebrow">Design og utvikling</span><h1>Samme identitet.<br><span>En ny opplevelse.</span></h1><p>Et nettsideprosjekt som kombinerer den opprinnelige Eldrehjelperne-profilen med et mer gjennomarbeidet design og en interaktiv forespørselsdemo.</p><div class="project-tags"><span>Figma</span><span>HTML og CSS</span><span>JavaScript</span><span>GPT og Codex</span></div></div></section>
<section class="section"><div class="container article-body"><span class="eyebrow">Utgangspunktet</span><h2>En vennlig merkevare,<br>med rom for forbedring.</h2><p>Den opprinnelige nettsiden hadde en tydelig identitet: en gul sol, turkise og marineblå flater, og vennlige illustrasjoner. Den nye versjonen bevarer dette, mens oppsett, typografi, navigasjon og interaksjoner er bearbeidet.</p><h2>Hva er endret?</h2><ul class="project-list"><li><strong>En tydeligere start.</strong> En kompakt navigasjon og en komponert førsteseksjon gjør tjenesten og neste steg enklere å forstå.</li><li><strong>Et samlet visuelt system.</strong> Felles farger, avstander, knapper og kort brukes på tvers av sidene.</li><li><strong>Et komplett kontaktforløp.</strong> Demoen har valg av tjeneste, validering, redigering av svar, oversikt og tydelig avslutning.</li><li><strong>Mer brukbar bevegelse.</strong> Små overganger støtter handlinger. Dekorativ bevegelse fjernes ved redusert bevegelse.</li></ul><h2>Merkevaren setter rammene.</h2><p>De fem grensesnittfargene er hentet fra originalfilen i Figma. Sollogoen og illustrasjonene er de originale bildefilene.</p><div class="palette-grid"><div style="--swatch:#00C4D7"><span></span><strong>Turkis</strong><code>#00C4D7</code></div><div style="--swatch:#173753"><span></span><strong>Marineblå</strong><code>#173753</code></div><div style="--swatch:#00F0FF"><span></span><strong>Elektrisk blå</strong><code>#00F0FF</code></div><div style="--swatch:#1B4353"><span></span><strong>Charcoal</strong><code>#1B4353</code></div><div style="--swatch:#FFFFFF"><span></span><strong>Hvit</strong><code>#FFFFFF</code></div></div><h2>En lett og oversiktlig løsning.</h2><p>Nettsiden er bygget med HTML, CSS og JavaScript, uten et stort grensesnittrammeverk. Innholdssidene virker uten JavaScript. JavaScript brukes til mobilmenyen, små overganger og forespørselsdemoen.</p><p>Skjemaet lagrer ikke kontaktopplysninger og har ingen servertilkobling. Før det kan brukes til ekte henvendelser, må mottak, validering på serveren og behandling av opplysninger implementeres.</p><h2>Utviklet med Figma og GPT.</h2><p>Figma brukes som referanse for den opprinnelige identiteten. GPT og Codex har bistått med planlegging, kode og kontroll. Denne siden beskriver implementasjonen, og hevder ikke at det er utført brukerundersøkelser eller målt effekt hos kunder.</p><h2>Se arbeidet og prøv selv.</h2><div class="hero-actions"><a class="button" href="kontakt.html">Prøv forespørselsdemoen {ARROW}</a><a class="text-link" href="https://github.com/akselistad/Eldrehjelperne">Se prosjektet på GitHub {ARROW}</a></div><p class="field-help">Kontaktdetaljer, teamroller og tilbud må kontrolleres med bedriften før offentlig lansering.</p></div></section>''')

page('personvern.html','Personvern i demoen – Eldrehjelperne UB','Slik fungerer opplysningene i nettsidens forespørselsdemo.','''<section class="section"><div class="container article-body"><a class="breadcrumb" href="index.html">Hjem /</a><span class="eyebrow">Om denne versjonen</span><h1>Personvern<br>i demoen.</h1><p class="lead">Forespørselsskjemaet er en demonstrasjon. Det sender ikke opplysninger til bedriften.</p><h2>Hva skjer med det du skriver?</h2><p>Opplysningene brukes bare for å vise skjemaets steg og oversikt i den åpne nettlesersiden. Nettsiden lagrer ikke skjemadata i informasjonskapsler eller lokal lagring. Når siden lastes på nytt, starter demoen på nytt.</p><p>Vi anbefaler at du bruker eksempelopplysninger og ikke oppgir sensitive opplysninger. Nettleseren din kan ha egne funksjoner for automatisk utfylling.</p><h2>Ingen analyseverktøy</h2><p>Denne versjonen inkluderer ikke analyseverktøy, sporingspiksler eller eksterne fonttjenester. Bilder og fonter lastes fra nettsidens egne filer.</p><h2>Telefon og e-post</h2><p>Telefonlenker og e-postlenker åpner appene dine. Hvis du velger å sende en e-post, behandles den utenfor skjemademoen.</p><h2>Før ekte innsending</h2><p>En fremtidig versjon med ekte innsending trenger informasjon om hvem som mottar opplysningene, hvorfor de samles inn, lagringstid og hvordan du kan henvende deg om dem. Denne demosiden er ikke en personvernerklæring for en slik fremtidig løsning.</p><a class="button" href="kontakt.html">Til kontaktsiden <span aria-hidden="true">↗</span></a></div></section>''')
print('Generated five complete pages')
